language:
 - c

compiler:
 - gcc

sudo: false
addons:
  apt:
    update: true
    packages:
     - build-essential
     - gnupg
     - realpath
     - util-linux
     - device-tree-compiler

git:
  submodules: false

install:
 - export CPUS="$C" && echo "CPUS='$CPUS'"
 - export PLATFORMS="$P" && echo "PLATFORMS='$PLATFORMS'"
 - export TARGETS="$T" && echo "TARGETS='$TARGETS'"
 - export FIRMWARE="$F" && echo "FIRMWARE='$FIRMWARE'"
 - $PWD/.travis/setup.sh

script:
 - $PWD/.travis/build.sh

after_success:
 - $PWD/.travis/update-prebuilt-list.sh

env:
  global:
   - HDMI2USB_UDEV_IGNORE=1
   - CLEAN_CHECK=1
   - PREBUILT_DIR="/tmp/HDMI2USB-firmware-prebuilt"
   # Travis reports incorrect the hosts number of processors, override to 2
   # cores.
   - JOBS=2
  matrix:
   # C=cpu.variant      TC="toolchain" P=platform         T="target1 t2"  F=firmware
   #--------------------------------------------
   # Bare-metal firmware, base targets
   #--------------------------------------------
   # LatticeMico32
   #--------------------------------------------
   # Linux Targets
   #--------------------------------------------
   # FIXME: Add vexriscv.linux
   - C=vexriscv.linux   TC="vivado"    P=arty              T="net"        F=linux
   #- C=vexriscv.linux   TC="ise"       P=opsis             T="net"        F=linux
   # FIXME: Add rocket.linux

jobs:
  allow_failures:
   - env: C=mor1kx.linux     TC="vivado"    P=nexys_video       T="net"        F=linux
   # Need to rebuilt Xilinx toolchain to add NeTV2 FPGA Part (Artix 7 35T+50T parts)
   - env: C=vexriscv         TC="vivado"    P=netv2             T="base net"
   - env: C=vexriscv         TC="vivado"    P=netv2             T="hdmi2pcie"
   # Occasionally these builds take longer than 50minute limit on Travis.
   - env: C=lm32             TC="ise"       P=atlys             T="hdmi2usb"
   - env: C=lm32             TC="ise"       P=opsis             T="hdmi2usb"
