name: lxbe-env
channels:
  - timvideos
dependencies:
  - fxload
  - icefunprog
  - iceprog
  - ninja
  - gperf
  - pyyaml
  - ipython
  - pyserial
  - nextpnr-ecp5
  - nextpnr-ice40
  - yosys
  - flterm
  - pip

